#!/bin/bash
git config --global  user.name "lokikkk"
git config --global  user.email "nwqdwjdwjdd33@gmail.com"



# Fix TimeZone
sudo ln -snf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

#tg
tg(){
	bot_api=$bot_api # Your tg bot api, dont use my one haha, it's better to encrypt bot api too.
	your_telegram_id=$1 # No need to touch 
	msg=$2 # No need to touch
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=markdown"
}

id=-1001282461032 # Your telegram id
tg $id "*SPARKOS_ROM _Compile _Status*: \TRIGGERED!\.
*Triggered _at*:- \$(date)\."

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -u https://github.com/exthmui/android.git -b exthm-11-g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
 
#device
git clone --depth=1 https://github.com/deathstroke0903/device_xiaomi_vince-1.git device/xiaomi/vince
git clone --depth=1 https://github.com/deathstroke0903/vendor_xiaomi_vince vendor/xiaomi/vince
git clone --depth=1 https://github.com/dotOS-Devices/android_kernel_xiaomi_vince kernel/xiaomi/vince
rm -rf hardware/qcom-caf/wlan && git clone https://android.googlesource.com/platform/hardware/qcom/wlan hardware/qcom-caf/wlan
rm -rf hardware/qcom-caf/msm8996/audio &&  git clone https://github.com/aseelps/hardware_qcom_audio_msm8996-vince hardware/qcom-caf/msm8996/audio
rm -rf hardware/qcom-caf/msm8996/media && git clone https://github.com/aseelps/hardware_qcom_media_msm8996-vince hardware/qcom-caf/msm8996/media
rm -rf hardware/qcom-caf/msm8996/display &&  git clone https://github.com/aseelps/hardware_qcom_display_msm8996-vince hardware/qcom-caf/msm8996/display

