#!/bin/bash

cd /tmp

# Compress function with pigz for faster compression
com ()
{
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

#tg
tg(){
        bot_api=$bot_api # Your tg bot api, dont use my one haha, it's better to encrypt bot api too.
        your_telegram_id=$1 # No need to touch
        msg=$2 # No need to touch
        curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=markdown"
}
id=-1001282461032 # Your telegram id
tg $id "*SPARKOS ROM Compile Status*:
*ccache uploading started at*:- \`$(date)\`."

#mkdir -p ~/.config/rclone
#echo "$rclone_config" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache
time rclone copy ccache.tar.gz ci:ccache -P # apon is my rclone config name (first line without [] of ~/.config/rclone/rclone.conf file from rclone setupped pc), ccache/ci2 is where ccache will be saved in m>
tg $id "*SPARKOS ROM Compile Status*:
*ccache uploaded at*:- \`$(date)\`."
